export const COSTUME_LIST_REQUEST = 'COSTUME_LIST_REQUEST';
export const COSTUME_LIST_SUCCESS = 'COSTUME_LIST_SUCCESS';
export const COSTUME_LIST_FAIL = 'COSTUME_LIST_FAIL';

export const COSTUME_DETAILS_REQUEST = 'COSTUME_DETAILS_REQUEST';
export const COSTUME_DETAILS_SUCCESS = 'COSTUME_DETAILS_SUCCESS';
export const COSTUME_DETAILS_FAIL = 'COSTUME_DETAILS_FAIL';

export const COSTUME_SAVE_REQUEST = 'COSTUME_SAVE_REQUEST';
export const COSTUME_SAVE_SUCCESS = 'COSTUME_SAVE_SUCCESS';
export const COSTUME_SAVE_FAIL = 'COSTUME_SAVE_FAIL';

export const COSTUME_DELETE_REQUEST = 'COSTUME_DELETE_REQUEST';
export const COSTUME_DELETE_SUCCESS = 'COSTUME_DELETE_SUCCESS';
export const COSTUME_DELETE_FAIL = 'COSTUME_DELETE_FAIL';
